const GENRES = [
        "Acoustic Blues",
        "Adult Alternative",
        "Adult Contemporary",
        "African",
        "Afrikaans",
        "Afro House",
        "Afro Soul",
        "Afro-Beat",
        "Afrobeats",
        "Afro-Pop",
        "Alternative",
        "Alternative & Rock in Spanish",
        "Alternative Country",
        "Alternative Folk",
        "Alternative Rap",
        "Ambient",
        "American Trad Rock",
        "Americana",
        "Anime",
        "Arabesque",
        "Arabic",
        "Arabic Pop",
        "Arena Rock",
        "Art Song",
        "Asia",
        "Assamese",
        "Australia",
        "Avant-Garde",
        "Avant-Garde Jazz",
        "Baile Funk",
        "Baroque Era",
        "Bass",
        "Bebop",
        "Benga",
        "Bengali",
        "Bhojpuri",
        "Big Band",
        "Bluegrass",
        "Blues",
        "Blues-Rock",
        "Bolero",
        "Bollywood",
        "Bongo-Flava",
        "Bossa Nova",
        "Brass & Woodwinds",
        "Brazilian",
        "Breakbeat",
        "British Invasion",
        "Britpop",
        "Cajun",
        "Calypso",
        "Cantata",
        "Cantopop",
        "Caribbean",
        "Carnatic Classical",
        "CCM",
        "Cello",
        "Celtic",
        "Celtic Folk",
        "Chachacha",
        "Chamber Music",
        "Chant",
        "Chanukah",
        "Chicago Blues",
        "Children's Music",
        "Chinese",
        "Chinese Alt",
        "Chinese Classical",
        "Chinese Flute",
        "Chinese Hip-Hop",
        "Chinese Opera",
        "Chinese Orchestral",
        "Chinese Regional Folk",
        "Chinese Rock",
        "Chinese Strings",
        "Choral",
        "Choro",
        "Christian & Gospel",
        "Christian Metal",
        "Christian Pop",
        "Christian Rap",
        "Christian Rock",
        "Christmas",
        "Christmas: Children's",
        "Christmas: Classic",
        "Christmas: Classical",
        "Christmas: Jazz",
        "Christmas: Modern",
        "Christmas: Pop",
        "Christmas: R&B",
        "Christmas: Religious",
        "Christmas: Rock",
        "Classic Blues",
        "Classic Christian",
        "Classic/Modern Dancehall",
        "Classical",
        "Classical Crossover",
        "Classical Era",
        "College Rock",
        "Comedy",
        "Contemporary Bluegrass",
        "Contemporary Blues",
        "Contemporary Celtic",
        "Contemporary Country",
        "Contemporary Era",
        "Contemporary Folk",
        "Contemporary Gospel",
        "Contemporary Jazz",
        "Contemporary Latin",
        "Contemporary R&B",
        "Contemporary Singer/Songwriter",
        "Cool",
        "Country",
        "Country Blues",
        "Country Gospel",
        "Coupé-Décalé",
        "C-Pop",
        "Crossover Jazz",
        "Cuban",
        "Dance",
        "Dangdut",
        "Death Metal/Black Metal",
        "Delta Blues",
        "Devotional & Spiritual",
        "Dini",
        "Dirty South",
        "Disco",
        "Disney",
        "Dixieland",
        "Doo Wop",
        "Downtempo",
        "Dub",
        "Dubstep",
        "Early Music",
        "East Coast Rap",
        "Easter",
        "Easy Listening",
        "Electric Blues",
        "Electronic",
        "Electronica",
        "EMO",
        "Enka",
        "Europe",
        "Fado",
        "Fantezi",
        "Farsi",
        "Film Soundtrack",
        "Fitness & Workout",
        "Flamenco",
        "Folk",
        "Folk-Rock",
        "Foreign Cinema",
        "Forró",
        "France",
        "French Pop",
        "Frevo",
        "Funk",
        "Fusion",
        "Gangsta Rap",
        "Garage",
        "German Folk",
        "German Pop",
        "Ghazals",
        "Glam Rock",
        "Gospel",
        "Goth Rock",
        "Gqom",
        "Grunge",
        "Guajira",
        "Guaracha",
        "Guitar",
        "Gujarati",
        "Hair Metal",
        "Halk",
        "Halloween",
        "Hard Bop",
        "Hard Rock",
        "Hardcore",
        "Hardcore Rap",
        "Haryanvi",
        "Hawaii",
        "Healing",
        "Heavy Metal",
        "Highlife",
        "Hindustani Classical",
        "Hip Hop/Rap",
        "Hip-Hop",
        "Holiday",
        "House",
        "Iberia",
        "IDM/Experimental",
        "Impressionist",
        "Indian",
        "Indian Classical",
        "Indian Folk",
        "Indian Pop",
        "Indie Pop",
        "Indie Rock",
        "Indo Pop",
        "Indonesian Religious",
        "Industrial",
        "Inspirational",
        "Instrumental",
        "Islamic",
        "Israeli",
        "Jam Bands",
        "Japan",
        "Jazz",
        "J-Pop",
        "Jungle/Drum'n'bass",
        "Kannada",
        "Karaoke",
        "Kayokyoku",
        "Khaleeji",
        "Kizomba",
        "Klezmer",
        "Korean",
        "Korean Folk-Pop",
        "Korean Hip-Hop",
        "Korean Indie",
        "Korean Rock",
        "Korean Traditional",
        "K-Pop",
        "Kuduro",
        "Kwaito",
        "Latin",
        "Latin Jazz",
        "Latin Rap",
        "Lounge",
        "Lovers Rock",
        "Lullabies",
        "Mainstream Jazz",
        "Malayalam",
        "Malaysian Pop",
        "Mambo",
        "Mandopop",
        "Manilla Sound",
        "Marathi",
        "Marching Bands",
        "Maskandi",
        "Mbalax",
        "Medieval Era",
        "Meditation",
        "Minimalism",
        "Modern Era",
        "Motown",
        "Musicals",
        "Nature",
        "Orchestral",
        "Original Score",
        "Percussion",
        "Piano",
        "Pop",
        "Pop in Spanish",
        "Pop Punk",
        "Pop/Rock",
        "Punk",
        "R&B/Soul",
        "Rajasthani",
        "Rap",
        "Reggae",
        "Reggaeton / Latin Urban",
        "Regional Indian",
        "Regional Mexicano",
        "Relaxation",
        "Religious",
        "Renaissance",
        "Rock",
        "Rock & Roll",
        "Rockabilly",
        "Sing-Along",
        "Singer/Songwriter",
        "Ska",
        "Smooth Jazz",
        "Soca",
        "Soft Rock",
        "Solo Instrumental",
        "Son",
        "Soukous",
        "Soul",
        "Sound Effects",
        "Soundtrack",
        "South Africa",
        "South America",
        "Southern Gospel",
        "Southern Rock",
        "Spoken Word",
        "Standards",
        "Standup Comedy",
        "Tango",
        "Techno",
        "Teen Pop",
        "Vocal",
        "Vocal Jazz",
        "Vocal Pop",
        "Wedding Music",
        "West Coast Rap",
        "World"     
].sort();

const LANGUAGES = [
    "Instrumental",
    "English",
    "Abkhazian",
    "Afar",
    "Afrikaans",
    "Akan",
    "Albanian",
    "Amharic",
    "Arabic",
    "Aragonese",
    "Armenian",
    "Assamese",
    "Avaric",
    "Avestan",
    "Aymara",
    "Azerbaijani",
    "Bambara",
    "Bashkir",
    "Basque",
    "Belarusian",
    "Bengali",
    "Bihari languages",
    "Bhojpuri",
    "Bislama",
    "Bosnian",
    "Breton",
    "Bulgarian",
    "Burmese",
    "Cantonese",
    "Catalan",
    "Central Khmer",
    "Chamorro",
    "Chechen",
    "Chichewa",
    "Chinese Simplified",
    "Chinese Traditional",
    "Church Slavic",
    "Chuvash",
    "Cornish",
    "Corsican",
    "Cree",
    "Croatian",
    "Czech",
    "Danish",
    "Divehi",
    "Dutch",
    "Dzongkha",
    "Esperanto",
    "Estonian",
    "Ewe",
    "Faroese",
    "Fijian",
    "Finnish",
    "French",
    "Fulah",
    "Gaelic",
    "Galician",
    "Ganda",
    "Georgian",
    "German",
    "Greek",
    "Guarani",
    "Gujarati",
    "Haitian",
    "Haryanvi",
    "Hausa",
    "Hebrew",
    "Herero",
    "Hindi",
    "Hiri Motu",
    "Hungarian",
    "Icelandic",
    "Ido",
    "Igbo",
    "Indonesian",
    "Interlingua",
    "Interlingue",
    "Inuktitut",
    "Inupiaq",
    "Irish",
    "Italian",
    "Japanese",
    "Javanese",
    "Kalaallisut",
    "Kannada",
    "Kanuri",
    "Kashmiri",
    "Kazakh",
    "Kikuyu",
    "Kinyarwanda",
    "Kirghiz",
    "Komi",
    "Kongo",
    "Konkani",
    "Korean",
    "Kuanyama",
    "Kurdish",
    "Lao",
    "Latin",
    "Latvian",
    "Limburgan",
    "Lingala",
    "Lithuanian",
    "Luba-Katanga",
    "Luxembourgish",
    "Macedonian",
    "Malagasy",
    "Malay",
    "Malayalam",
    "Maltese",
    "Mandarin",
    "Manx",
    "Maori",
    "Marathi",
    "Marshallese",
    "Mongolian",
    "Nauru",
    "Navajo",
    "Ndonga",
    "Nepali",
    "North Ndebele",
    "Northern Sami",
    "Norwegian",
    "Norwegian Bokmål",
    "Norwegian Nynorsk",
    "Occitan",
    "Ojibwa",
    "Oriya",
    "Oromo",
    "Ossetian",
    "Pali",
    "Pashto",
    "Persian",
    "Polish",
    "Portuguese",
    "Punjabi",
    "Quechua",
    "Rajasthani",
    "Romanian",
    "Romansh",
    "Rundi",
    "Russian",
    "Samoan",
    "Sango",
    "Sanskrit",
    "Sardinian",
    "Serbian",
    "Shona",
    "Sichuan Yi",
    "Sindhi",
    "Sinhala",
    "Slovak",
    "Slovenian",
    "Somali",
    "South Ndebele",
    "Southern Sotho",
    "Spanish",
    "Spanish (Latin America)",
    "Sundanese",
    "Swahili",
    "Swati",
    "Swedish",
    "Tagalog",
    "Tahitian",
    "Tajik",
    "Tamil",
    "Tatar",
    "Telugu",
    "Thai",
    "Tibetan",
    "Tigrinya",
    "Tonga",
    "Tsonga",
    "Tswana",
    "Turkish",
    "Turkmen",
    "Twi",
    "Uighur",
    "Ukrainian",
    "Urdu",
    "Uzbek",
    "Venda",
    "Vietnamese",
    "Volapük",
    "Walloon",
    "Welsh",
    "Western Frisian",
    "Wolof",
    "Xhosa",
    "Yiddish",
    "Yoruba",
    "Zhuang",
    "Zulu"
].sort();

const DISTRIBUTION_STORES = [
    "iTunes/Apple Music",
    "Deezer",
    "Spotify",
    "YouTube Music",
    "Tidal",
    "Amazon",
    "Rhapsody/Napster",
    "Nuuday",
    "Pandora",
    "KKBOX",
    "iMusica",
    "Soundcloud",
    "iHeartRadio",
    "Anghami",
    "Jiosaavn",
    "AWA",
    "Tencent",
    "NetEase",
    "YouTube Content ID",
    "Facebook Audio Library",
    "Facebook Rights Manager",
    "Mixcloud",
    "TikTok",
    "Boomplay",
    "Snap",
    "Peloton",
    "Audiomack",
    "Trebel",
    "JOOX",
    "Flo",
    "Lickd"
].sort();

window.GENRES = GENRES;
window.LANGUAGES = LANGUAGES;
window.DISTRIBUTION_STORES = DISTRIBUTION_STORES;
