[build]
  publish = "/"
  command = "# no build command needed"

[[redirects]]
  from = "/*.html"
  to = "/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/dashboard.html"
  to = "/dashboard"
  status = 301
  force = true

[[redirects]]
  from = "/admin.html"
  to = "/admin"
  status = 301
  force = true

[[redirects]]
  from = "/submit.html"
  to = "/submit"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
